name: Auto Downmerge Main to Develop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  downmerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Add a delay to avoid race conditions
        run: sleep 10 

      - name: create pull-request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            gh pr create --base develop --title "Automatic merge main into develop" --body 'Created by Github action' --assignee "${{ github.actor }}"
      - name: get release branches
        run: |
            git fetch --all
            export BRANCHES=$(git branch -r | grep 'release/' | sed 's/origin\///')
            if [ -z "$BRANCHES" ]; then
              echo "No release branches found."
            else
              echo "$BRANCHES"
            fi