name: Auto Downmerge Main to Develop
on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  get-base-branches: # finds the earliest release branch if it exists
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ${{ success() }}
    outputs:
      baseBranch: ${{ steps.earliestRelease.outputs.baseBranch }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: get release branches
        id: earliestRelease
        run: |
            changedBranch=${GITHUB_REF#refs/heads/} #This gets the base of the pr that triggered this workflow
            git fetch --all
            export BRANCHES=$(git branch -r | grep 'release/' | sed 's/origin\///')
            baseBranch=""
            branchFound=false
            if [ -z "$BRANCHES" ]; then
              echo "No release branches found."
              echo "baseBranch=develop" >> "$GITHUB_OUTPUT"
              exit 0;
            else
              branches=$(git branch -r | grep 'release/' | sed 's/origin\///' | sed 's/release\///')

              # Pad single-digit components with a leading zero and sort
              sorted_branches=$(echo "$branches" | awk -F. '
                {
                  # Pad each component with a leading zero if needed
                  for (i=1; i<=NF; i++) {
                    if (length($i) == 1) 
                      $i = $i"0";
                  }
                  # Output the padded version string
                  print $0
                }' | sort -V)
              # Add back the release/ prefix
              sorted_branches=$(echo "$sorted_branches" | sed 's/^/release\//')
              if [ "$changedBranch" = "main" ]; then
                # If the changed branch is main, we need the oldest branch
                baseBranch="release/$(echo "$sorted_branches" | head -n 1)"
              else
                # For release branches, find the next branch after the changedBranch
                for branch in $sorted_branches; do
                  current_version=${branch#release/}
                  if [ "$branchFound" = true ]; then
                    baseBranch="release/$branch"
                    break
                  fi
                  # Check if the current branch is the changedBranch
                  if [ "$branch" = "$changedBranch" ]; then
                    branchFound=true
                  fi
                done
                # If no next branch was found, default to the changedBranch itself
                if [ -z "$baseBranch" ]; then
                  echo "No next branch found. Staying on $changedBranch."
                  baseBranch="develop"
                fi
              fi
            echo "Base branch is $baseBranch."
            echo "baseBranch=$baseBranch" >> "$GITHUB_OUTPUT"
                      fi
                      echo "baseBranch=$baseBranch" >> "$GITHUB_OUTPUT"

      - name: Branches list
        run: echo "The branches are ${{ steps.earliestRelease.outputs.baseBranch }}"

  downmerge-main: # creates the pr's to the branch returned from the get-base-branches job
    runs-on: ubuntu-latest
    needs: [get-base-branches]
    if: github.event_name == 'push' && ${{ success() }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Fetch to the latest state of main branch
        run: git pull origin main

      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          changedBranch=${GITHUB_REF#refs/heads/} >> "$GITHUB_OUTPUT" #This gets the base of the pr that triggered this workflow
          # Attempt to list PRs
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --head '$changedBranch' \
              --base '${{ needs.get-base-branches.outputs.baseBranch }}' \
              --json title \
              --jq 'length' || echo "Error")
          echo "PRs count: $prs"
          echo "Changes were pushed to branch: $changedBranch"
          if [[ "$prs" == "Error" ]]; then
            echo "The workflow encountered a problem."
            exit 1
          elif ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          else
              echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Debug skip variable
        run: echo "The skip variable is set to ${{ steps.check.outputs.skip }}"

      - name: Create pull request
        if: ${{ steps.check.outputs.skip  == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --base ${{ needs.get-base-branches.outputs.baseBranch }} --title "Automatic merge ${{ steps.check.outputs.changedBranch }} into ${{ needs.get-base-branches.outputs.baseBranch }}" --body 'Created by GitHub action' --assignee "${{ github.actor }}"

      - name: PR Already Exists Message
        if: ${{ steps.check.outputs.skip  == 'true' }}
        run: echo "A pull request from main to ${{ needs.get-base-branches.outputs.baseBranch }} already exists, skipping creation."
