name: Auto Downmerge Main to Develop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  downmerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          

      - name: pull-request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            gh pr create --base develop --title "Merge main into develop" --body 'Created by Github action'