name: Auto Downmerge Main to Develop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  downmerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"

      - name: Create Pull Request
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin
          git checkout develop
          git merge main
          git push origin develop

      - name: I break things
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: ""
          destination_branch: "develop"               
          pr_title: "Pulling ${{ github.ref }} into develop"
          pr_body: |
            :crown: *An automated PR*
          pr_reviewer: "{{ github.event.pull_request.user.login }}"
          pr_label: "auto-generated-pr"